'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState, type ReactNode } from 'react';
import { useTranslations } from 'next-intl';
import { IconButton, Logo } from '../../../../packages/ui/src/index';
import { demoSeed, useDemo } from './demo-context';
const navigation = [['home', '/'], ['administrative', '/administrativa'], ['operations', '/operaciones'], ['accounting', '/contabilidad'], ['people', '/personas'], ['teams', '/equipos'], ['providers', '/proveedores'], ['reports', '/informes'], ['settings', '/configuracion']] as const;
const projectTabs = [['overview', 'resumen'], ['list', 'lista'], ['board', 'tablero'], ['calendar', 'calendario'], ['timeline', 'cronograma'], ['documents', 'documentos'], ['forms', 'formularios'], ['validations', 'validaciones'], ['projectReports', 'informes']] as const;
export function AppShell({ children }: { children: ReactNode }) {
  const t = useTranslations('app'); const pathname = usePathname(); const [open, setOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const [confirming, setConfirming] = useState(false); const [resetNotice, setResetNotice] = useState(false); const { phId, phName, actor, setPhId, setActorId, reset } = useDemo(); const projectBase = pathname.startsWith('/operaciones/') ? '/operaciones/mantenimiento' : null; const demoMode = process.env.NODE_ENV !== 'production';
  const actors = demoSeed.people.filter((person) => person.phId === phId && person.status === 'ACTIVE');
  return <div className={`shell ${collapsed ? 'collapsed' : ''}`}><IconButton className="mobile-menu" label={t('menu')} aria-expanded={open} onClick={() => setOpen(!open)}>☰</IconButton><aside className={open ? 'open' : ''}><div className="brand"><Logo /><span>{t('name')}</span></div><IconButton className="collapse" label={t('collapse')} onClick={() => setCollapsed(!collapsed)}>‹</IconButton><nav aria-label="Navegación principal">{navigation.map(([key, href]) => <Link key={key} href={href} aria-current={pathname === href || (href !== '/' && pathname.startsWith(`${href}/`)) ? 'page' : undefined} onClick={() => setOpen(false)}>{t(key)}</Link>)}</nav></aside><main><header><div className="demo-controls"><label>PH<select aria-label="Seleccionar propiedad horizontal" value={phId} onChange={(event) => setPhId(event.target.value)}>{demoSeed.contexts.map((context) => <option key={context.id} value={context.id}>{context.name}</option>)}</select></label><label>Usuario<select aria-label="Seleccionar usuario de demostración" value={actor.id} onChange={(event) => setActorId(event.target.value)}>{actors.map((person) => <option key={person.id} value={person.id}>{person.displayName} · {person.role === 'ADMIN' ? 'Administrador' : 'Colaborador'}</option>)}</select></label><span> · Contexto de demostración</span></div>{demoMode && <IconButton className="profile" label="Restablecer datos de demostración" onClick={() => setConfirming(true)}>↺</IconButton>}</header>{resetNotice && <p role="status" className="reset-notice">Datos de demostración restablecidos.</p>}{confirming && <section className="reset-dialog" role="alertdialog" aria-modal="true" aria-label="Restablecer demostración"><p>¿Restablecer los datos de demostración? Se perderán los cambios locales.</p><button className="tm-button tm-button--secondary" onClick={() => setConfirming(false)}>Cancelar</button><button className="tm-button" onClick={() => { reset(); setConfirming(false); setResetNotice(true); }}>Restablecer</button></section>}{projectBase && <><section className="project-header"><p className="eyebrow">Gestión operativa</p><h1>Mantenimiento preventivo</h1></section><nav className="project-tabs" aria-label="Navegación del proyecto">{projectTabs.map(([key, slug]) => { const href = `${projectBase}/${slug}`; return <Link key={slug} href={href} aria-current={pathname === href ? 'page' : undefined}>{t(key)}</Link>; })}</nav></>}{children}</main></div>;
}
