'use client';
/* eslint-disable react-hooks/set-state-in-effect -- repository reads occur after client mount. */

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { demoIds, type RepositoryError } from '@task-manager/data';
import { Button, ConflictState, StatusBadge } from '../../../../packages/ui/src/index';
import type { Person, Project, Team, WorkItem } from '@task-manager/shared';
import { useDemo } from './demo-context';

const moduleBySegment: Record<string, Project['module']> = { administrativa: 'ADMINISTRATIVE', operaciones: 'OPERATIONS', contabilidad: 'ACCOUNTING' };
const moduleName: Record<Project['module'], string> = { ADMINISTRATIVE: 'Gestión administrativa', OPERATIONS: 'Gestión operativa', ACCOUNTING: 'Gestión de contabilidad' };
const templates: Record<Project['module'], { name: string; description: string }> = { ADMINISTRATIVE: { name: 'Atención administrativa', description: 'Solicitudes, comunicaciones y coordinación administrativa.' }, OPERATIONS: { name: 'Operación del edificio', description: 'Mantenimiento, limpieza, seguridad e incidencias.' }, ACCOUNTING: { name: 'Seguimientos de cobro', description: 'Cuentas por cobrar y seguimiento contable.' } };
const teamTypes: Team['type'][] = ['ADMINISTRATION', 'OPERATIONS', 'CLEANING', 'MAINTENANCE', 'SECURITY', 'ACCOUNTING', 'OTHER'];

function ErrorNotice({ error, onRetry }: { error: RepositoryError | null; onRetry?: () => void }) { if (!error) return null; if (error.code === 'CONFLICT') return <ConflictState onReload={() => window.location.reload()} onRetry={onRetry} />; return <section className="tm-state tm-state--error" role="alert"><p>{error.message}</p>{onRetry && <Button variant="secondary" onClick={onRetry}>Reintentar</Button>}</section>; }
export function WorkspaceContent({ segments }: { segments: string[] }) {
  const { phId } = useDemo(); const requestedPhId = useSearchParams().get('phId');
  if (requestedPhId && requestedPhId !== phId) return <section className="tm-state tm-state--error" role="alert"><h2>Acceso denegado</h2><p>Esta URL solicita una PH distinta de tu contexto permitido. Cambia al contexto autorizado desde el encabezado.</p></section>;
  if (segments.includes('validaciones')) return <ValidationPanel />;
  const section = segments[0] ?? ''; if (section === 'personas') return <PeoplePage />; if (section === 'equipos') return <TeamsPage />; if (!section) return <HomePage />; return <ProjectsPage module={moduleBySegment[section]} />;
}
function ValidationPanel() {
  const { phId, actor, repository } = useDemo(); const [items, setItems] = useState<WorkItem[] | null>(null); const [error, setError] = useState<RepositoryError | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(() => { setError(null); void repository.listWorkItems({ phId, projectId: demoIds.opsProject }).then((page) => setItems(page.items)).catch(setError); }, [repository, phId]); useEffect(load, [load]);
  const submitEvidence = (item: WorkItem) => void repository.submitEvidence({ id: item.id, phId, version: item.version, evidenceUrl: `https://demo.local/evidence/${item.id}.jpg` }).then(() => { setNotice('Evidencia enviada para revisión.'); load(); }).catch(setError);
  const review = (item: WorkItem, decision: 'APPROVED' | 'REJECTED') => void repository.reviewWorkItem({ id: item.id, phId, decision, comment: decision === 'REJECTED' ? 'La evidencia no permite validar el trabajo.' : undefined, version: item.version }).then(() => { setNotice(decision === 'APPROVED' ? 'Trabajo aprobado.' : 'Trabajo rechazado con comentario.'); load(); }).catch(setError);
  return <section className="workspace-page"><p className="eyebrow">Gestión operativa</p><h1>Validaciones</h1><p>Demostración de evidencia y aprobación según el rol seleccionado.</p>{notice && <p role="status">{notice}</p>}{error && <ErrorNotice error={error} onRetry={load} />}{!items ? <div className="tm-skeleton" /> : items.length === 0 ? <section className="tm-state"><h2>Sin resultados</h2><p>No hay evidencias pendientes en este proyecto.</p></section> : <ul className="entity-list">{items.map((item) => <li key={item.id}><div><strong>{item.key} · {item.title}</strong><span>Evidencia: {item.evidenceUrl ? 'adjunta' : 'pendiente'} · Validación: {item.validationStatus}</span>{item.validationComment && <small>{item.validationComment}</small>}</div><div>{actor.role === 'ADMIN' ? <><Button variant="secondary" disabled={item.validationStatus !== 'PENDING'} onClick={() => review(item, 'REJECTED')}>Rechazar</Button><Button disabled={item.validationStatus !== 'PENDING'} onClick={() => review(item, 'APPROVED')}>Aprobar</Button></> : <Button disabled={item.assigneeId !== actor.id} onClick={() => submitEvidence(item)}>Enviar evidencia</Button>}</div></li>)}</ul>}</section>;
}
function HomePage() {
  const { phId, repository, phName } = useDemo(); const [data, setData] = useState<{ projects: Project[]; people: Person[]; teams: Team[] } | null>(null);
  const load = useCallback(() => { void Promise.all([repository.listProjects({ phId }), repository.listPeople({ phId }), repository.listTeams({ phId })]).then(([projects, people, teams]) => setData({ projects, people, teams })); }, [repository, phId]); useEffect(load, [load]);
  if (!data) return <section className="tm-state" aria-busy="true"><p>Cargando inicio…</p></section>;
  return <section className="workspace-page"><p className="eyebrow">{phName}</p><h1>Inicio del PH</h1><p>Una vista contextual de los proyectos y equipos a los que tienes acceso.</p><div className="metric-grid"><article><strong>{data.projects.length}</strong><span>Proyectos autorizados</span></article><article><strong>{data.teams.length}</strong><span>Equipos activos</span></article><article><strong>{data.people.length}</strong><span>Personas activas</span></article></div><h2>Accesos rápidos</h2><div className="quick-links"><Link href="/administrativa">Administración</Link><Link href="/operaciones">Operaciones</Link><Link href="/contabilidad">Contabilidad</Link><Link href="/personas">Personas</Link><Link href="/equipos">Equipos</Link></div></section>;
}
function ProjectsPage({ module }: { module?: Project['module'] }) {
  const { phId, actor, repository } = useDemo(); const [projects, setProjects] = useState<Project[] | null>(null); const [showArchived, setShowArchived] = useState(false); const [error, setError] = useState<RepositoryError | null>(null); const [creating, setCreating] = useState(false);
  const load = useCallback(() => { setError(null); void repository.listProjects({ phId, module, includeArchived: showArchived }).then(setProjects).catch((e: RepositoryError) => setError(e)); }, [repository, phId, module, showArchived]); useEffect(load, [load]);
  if (!module) return <section className="tm-state"><h1>Vista en preparación</h1><p>Esta sección no forma parte del alcance del épico de organización.</p></section>;
  const archive = (project: Project) => void repository.setProjectArchived(phId, project.id, project.status === 'ACTIVE', project.version).then(load).catch(setError);
  return <section className="workspace-page"><p className="eyebrow">{moduleName[module]}</p><h1>Proyectos</h1><p>Plantilla disponible: {templates[module].name}. {module === 'ADMINISTRATIVE' ? 'No incluye contratos ni renovaciones.' : module === 'ACCOUNTING' ? 'Incluye seguimientos de cobro.' : ''}</p><div className="toolbar"><label><input type="checkbox" checked={showArchived} onChange={(e) => setShowArchived(e.target.checked)} /> Mostrar archivados</label>{actor.role === 'ADMIN' && <Button onClick={() => setCreating(!creating)}>{creating ? 'Cerrar formulario' : 'Crear proyecto'}</Button>}</div>{creating && <ProjectForm module={module} onDone={() => { setCreating(false); load(); }} onError={setError} />}{error?.code === 'ACCESS_DENIED' ? <section className="tm-state tm-state--error"><h2>Acceso denegado</h2><p>No tienes acceso a este módulo.</p></section> : <><ErrorNotice error={error} onRetry={load} />{!projects ? <div className="tm-skeleton" /> : projects.length === 0 ? <section className="tm-state"><h2>Sin proyectos</h2><p>Crea un proyecto desde la plantilla del módulo.</p></section> : <ul className="project-list">{projects.map((project) => <li key={project.id}><div><strong><i style={{ backgroundColor: project.color }} />{project.key} · {project.name}</strong><span>{project.description ?? 'Sin descripción'}</span></div><div><StatusBadge tone={project.status === 'ARCHIVED' ? 'warning' : 'success'}>{project.status === 'ARCHIVED' ? 'Archivado' : 'Activo'}</StatusBadge>{actor.role === 'ADMIN' && <Button variant="secondary" onClick={() => archive(project)}>{project.status === 'ACTIVE' ? 'Archivar' : 'Restaurar'}</Button>}</div></li>)}</ul>}</>}</section>;
}
function ProjectForm({ module, onDone, onError }: { module: Project['module']; onDone: () => void; onError: (e: RepositoryError) => void }) { const { phId, repository } = useDemo(); const temp = templates[module]; const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); void repository.createProject({ phId, module, name: String(form.get('name')), key: String(form.get('key')), description: String(form.get('description')) || undefined, color: String(form.get('color')) || undefined }).then(onDone).catch(onError); }; return <form className="entity-form" onSubmit={submit}><label>Nombre<input name="name" required defaultValue={temp.name} /></label><label>Clave visible<input name="key" required maxLength={10} pattern="[A-Za-z]{2,10}" placeholder="EJ: OPS" /></label><label>Descripción<textarea name="description" defaultValue={temp.description} /></label><label>Color<input name="color" type="color" defaultValue="#4583bd" /></label><Button type="submit">Guardar proyecto</Button></form>; }
function PeoplePage() { const { phId, actor, repository } = useDemo(); const [people, setPeople] = useState<Person[] | null>(null); const [error, setError] = useState<RepositoryError | null>(null); const [creating, setCreating] = useState(false); const load = useCallback(() => void repository.listPeople({ phId, includeInactive: true }).then(setPeople).catch(setError), [repository, phId]); useEffect(load, [load]); const visibleId = actor.role === 'ADMIN'; return <section className="workspace-page"><p className="eyebrow">Organización</p><h1>Personas</h1><p>Las tarjetas protegen el identificador personal; solo el rol administrativo lo revela.</p><div className="toolbar">{actor.role === 'ADMIN' && <Button onClick={() => setCreating(!creating)}>{creating ? 'Cerrar formulario' : 'Agregar persona'}</Button>}</div>{creating && <PersonForm onDone={() => { setCreating(false); load(); }} onError={setError} />}<ErrorNotice error={error} onRetry={load} />{!people ? <div className="tm-skeleton" /> : <ul className="entity-list">{people.map((person) => <li key={person.id}><div><strong>{person.displayName}</strong><span>{person.jobTitle ?? 'Sin cargo'} · {person.role === 'ADMIN' ? 'Administrador' : 'Colaborador'}</span>{visibleId && <small>Cédula: {person.nationalId}</small>}</div><StatusBadge tone={person.status === 'ACTIVE' ? 'success' : 'warning'}>{person.status === 'ACTIVE' ? 'Activo' : 'Inactivo'}</StatusBadge></li>)}</ul>}</section>; }
function PersonForm({ onDone, onError }: { onDone: () => void; onError: (e: RepositoryError) => void }) { const { phId, repository } = useDemo(); const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const firstName = String(f.get('firstName')); const lastName = String(f.get('lastName')); void repository.createPerson({ phId, firstName, lastName, displayName: `${firstName} ${lastName}`, nationalId: String(f.get('nationalId')), jobTitle: String(f.get('jobTitle')) || undefined, role: String(f.get('role')) as Person['role'], status: 'ACTIVE' }).then(onDone).catch(onError); }; return <form className="entity-form" onSubmit={submit}><label>Nombre<input name="firstName" required /></label><label>Apellido<input name="lastName" required /></label><label>Cédula<input name="nationalId" required /></label><label>Cargo<input name="jobTitle" /></label><label>Rol<select name="role"><option value="COLLABORATOR">Colaborador</option><option value="ADMIN">Administrador</option></select></label><Button>Guardar persona</Button></form>; }
function TeamsPage() { const { phId, actor, repository } = useDemo(); const [teams, setTeams] = useState<Team[] | null>(null); const [people, setPeople] = useState<Person[]>([]); const [error, setError] = useState<RepositoryError | null>(null); const [creating, setCreating] = useState(false); const load = useCallback(() => { void Promise.all([repository.listTeams({ phId, includeArchived: true }), repository.listPeople({ phId })]).then(([nextTeams, nextPeople]) => { setTeams(nextTeams); setPeople(nextPeople); }).catch(setError); }, [repository, phId]); useEffect(load, [load]); const archive = (team: Team) => void repository.setTeamArchived(phId, team.id, team.status === 'ACTIVE', team.version).then(load).catch(setError); return <section className="workspace-page"><p className="eyebrow">Organización</p><h1>Equipos</h1><p>Las membresías son muchos-a-muchos: una persona puede formar parte de varios equipos y los equipos pueden servir a distintos proyectos o tableros.</p><div className="toolbar">{actor.role === 'ADMIN' && <Button onClick={() => setCreating(!creating)}>{creating ? 'Cerrar formulario' : 'Crear equipo'}</Button>}</div>{creating && <TeamForm people={people} onDone={() => { setCreating(false); load(); }} onError={setError} />}<ErrorNotice error={error} onRetry={load} />{!teams ? <div className="tm-skeleton" /> : <ul className="entity-list">{teams.map((team) => { const lead = people.find((person) => person.id === team.leadId); return <li key={team.id}><div><strong>{team.name}</strong><span>Líder: {lead?.displayName ?? 'Sin asignar'} · {team.memberIds.length} miembros · 0 pendientes</span><small>{team.memberIds.map((id) => people.find((p) => p.id === id)?.displayName).filter(Boolean).join(', ') || 'Sin miembros'}</small></div><div><StatusBadge tone={team.status === 'ACTIVE' ? 'success' : 'warning'}>{team.status === 'ACTIVE' ? 'Activo' : 'Archivado'}</StatusBadge>{actor.role === 'ADMIN' && <Button variant="secondary" onClick={() => archive(team)}>{team.status === 'ACTIVE' ? 'Archivar' : 'Restaurar'}</Button>}</div></li>; })}</ul>}</section>; }
function TeamForm({ people, onDone, onError }: { people: Person[]; onDone: () => void; onError: (e: RepositoryError) => void }) { const { phId, repository } = useDemo(); const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const memberIds = f.getAll('members').map(String); void repository.createTeam({ phId, name: String(f.get('name')), type: String(f.get('type')) as Team['type'], description: String(f.get('description')) || undefined, leadId: String(f.get('leadId')) || undefined, memberIds }).then(async (team) => { await repository.setTeamMembers(phId, team.id, memberIds); onDone(); }).catch(onError); }; return <form className="entity-form" onSubmit={submit}><label>Nombre<input name="name" required /></label><label>Tipo<select name="type">{teamTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Líder<select name="leadId"><option value="">Sin asignar</option>{people.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><fieldset><legend>Miembros</legend>{people.map((person) => <label key={person.id}><input type="checkbox" name="members" value={person.id} /> {person.displayName}</label>)}</fieldset><label>Descripción<textarea name="description" /></label><Button>Guardar equipo</Button></form>; }
